### ISSUE TITLE
Nie działa

### ISSUE THREAD

**Issue by artur9010** [PabloTL/PabloLogowanie#2]
Ten szajz nie dziaua1!!!1!!!!...
napraw wwwww toooooo!@$REFGFDFBGDFGHDFBFHDBwWQ#R#%#RFF@

**Comment by northpl93** [comment]
Próbowałeś wyłączyć i włączyć?

**Comment by PabloTL** [comment]
Ile masz ramu?

**Comment by MrGregorix** [comment]
U mnie też nie działa, mam 256k ramu i odpalam to na kalkulatorze!

**Comment by artur9010** [comment]
@NorthPL dzienki, jusz działa!!!!
@PabloTL 64GB
@MrGregorix ja na loduwce
