### ISSUE TITLE
Szyfrowanie haseł

### ISSUE THREAD

**Issue by northpl93** [PabloTL/PabloLogowanie#4]
Proponuję dodać szyfrowanie haseł przez [CSS3](https://pl.wikipedia.org/wiki/Kaskadowe_arkusze_styl%C3%B3w)

**Comment by artur9010** [comment]
Jestem za!

**Comment by MrGregorix** [comment]
hyba jesteś gupi; przeciesz kaszty wię rze najlepjej do szyfrowanja uszywać brajnfuka

**Comment by MarcinWieczorek** [comment]
Przecież dla bukkita dedykowany jest algorytm md_5

**Comment by artur9010** [comment]
@md5

**Comment by northpl93** [comment]
chyba nie doczekam się ficzera, zamykam
